ClubBundle\Entity\Event:
    type: entity
    table: null
    repositoryClass: ClubBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
            column: Titre
        description:
            type: string
            length: 255
            column: Description
        photo:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
